# sort b,a,c


b=aaaaaaaaa # 8 + 1
ca=ac

aaaaaaaaac=


BBBBBBBc=(return)false
=(return)true

#

b=zzzzzzzz # 4 * 2
c=zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz # 8 * 4

zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz=
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz=C
zzzzzzzzz=
zzzzzzzz=B

#

b=zzzzzzzzzzzzzzzzz # 16 + 1
c=zzzzzzzzzzzzzzzz # 16
za=az
aa=(return)false

az=
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz=
zzzzzzzzzzzzzzzz=C


azzyyyycccc